-- ===============================================
-- AI Interviewer Analyzer - Schema Fix (Version 2)
-- ===============================================
-- Copy and run this in your Supabase SQL Editor to perfectly match the Next.js app's data!

-- 1. We must drop the old, incorrect Interviews table
DROP TABLE IF EXISTS public."Interviews";

-- 2. Create the exact table structure the frontend expects
CREATE TABLE public."Interviews" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id TEXT UNIQUE NOT NULL,
    "userEmail" TEXT NOT NULL REFERENCES public."Users"(email) ON DELETE CASCADE,
    "jobPosition" TEXT NOT NULL,
    "jobDescription" TEXT NOT NULL,
    "type" JSONB,
    "duration" INTEGER NOT NULL,
    "questionList" JSONB,
    "interview-feedback" JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Re-apply the Row-Level Security!
ALTER TABLE public."Interviews" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only view their own interviews" ON public."Interviews" FOR SELECT USING (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only insert their own interviews" ON public."Interviews" FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only update their own interviews" ON public."Interviews" FOR UPDATE USING (auth.jwt() ->> 'email' = "userEmail") WITH CHECK (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only delete their own interviews" ON public."Interviews" FOR DELETE USING (auth.jwt() ->> 'email' = "userEmail");
