-- ==========================================
-- AI Interviewer Analyzer - Supabase Schema
-- ==========================================
-- Copy and paste this entirely into your Supabase SQL Editor to set up your database.

-- 1. Create the Users table
CREATE TABLE IF NOT EXISTS public."Users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    credits INTEGER DEFAULT 3,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the Interviews table
CREATE TABLE IF NOT EXISTS public."Interviews" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id TEXT UNIQUE NOT NULL,
    "userEmail" TEXT NOT NULL REFERENCES public."Users"(email) ON DELETE CASCADE,
    "jobPosition" TEXT NOT NULL,
    "jobDesc" TEXT NOT NULL,
    "jobExperience" TEXT NOT NULL,
    "interviewDuration" INTEGER NOT NULL,
    "jsonMockResp" JSONB,
    "interview-feedback" JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Set up Row Level Security (RLS) for public access during development
ALTER TABLE public."Users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Interviews" ENABLE ROW LEVEL SECURITY;

-- Security Policies for Users
-- Only the user whose authenticated email matches the row can view/modify it
CREATE POLICY "Users can only view their own profile" ON public."Users" FOR SELECT USING (auth.jwt() ->> 'email' = email);
CREATE POLICY "Users can only insert their own profile" ON public."Users" FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = email);
CREATE POLICY "Users can only update their own profile" ON public."Users" FOR UPDATE USING (auth.jwt() ->> 'email' = email) WITH CHECK (auth.jwt() ->> 'email' = email);

-- Security Policies for Interviews
-- Only the user who created the interview can access or modify it
CREATE POLICY "Users can only view their own interviews" ON public."Interviews" FOR SELECT USING (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only insert their own interviews" ON public."Interviews" FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only update their own interviews" ON public."Interviews" FOR UPDATE USING (auth.jwt() ->> 'email' = "userEmail") WITH CHECK (auth.jwt() ->> 'email' = "userEmail");
CREATE POLICY "Users can only delete their own interviews" ON public."Interviews" FOR DELETE USING (auth.jwt() ->> 'email' = "userEmail");
